openapi: 3.0.0
info:
  title: SNS API
  description: |
    # 概要
    本ドキュメントはSNSアプリのAPI仕様書です。
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /auth:
    $ref: './auth/auth.yaml'
  /account:
    $ref: './account/account.yaml'
  /account/profile:
    $ref: './account/profile.yaml'
  /account/icon_image:
    $ref: './account/icon_image.yaml'
  /posts:
    $ref: './post/post.yaml'
  /posts/{id}:
    $ref: './post/post_id.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
