openapi: 3.0.0
info:
  title: SNS API
  description: |
    # 概要
    本ドキュメントはSNSアプリのAPI仕様書です。
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /auth:
    post:
      tags:
        - Auth
      summary: サインイン
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: メールアドレス
                password:
                  type: string
                  description: パスワード
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  user:
                    type: object
                    required:
                      - id
                      - name
                      - email
                    properties:
                      id:
                        type: integer
                        format: int32
                      name:
                        type: string
                      email:
                        type: string
                      icon_image:
                        type: string
                  token:
                    type: string
                    description: このtokenをヘッダーに入れて認証
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
    delete:
      tags:
        - Auth
      summary: サインアウト
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - deviceId
              properties:
                deviceId:
                  type: string
                  description: 端末固有のID
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                required:
                  - success
                properties:
                  success:
                    type: boolean
  /account:
    get:
      tags:
        - アカウント
      summary: 取得
      security:
        - BearerAuth: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    required:
                      - id
                      - name
                      - email
                    properties:
                      id:
                        type: integer
                        format: int32
                      name:
                        type: string
                      email:
                        type: string
                      icon_image:
                        type: string
    post:
      tags:
        - アカウント
      summary: 作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                user:
                  type: object
                  required:
                    - name
                    - email
                    - password
                  properties:
                    name:
                      type: string
                      description: 名前
                    email:
                      type: string
                      description: メールアドレス
                    password:
                      type: string
                      description: パスワード
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  user:
                    type: object
                    required:
                      - id
                      - name
                      - email
                    properties:
                      id:
                        type: integer
                        format: int32
                      name:
                        type: string
                      email:
                        type: string
                      icon_image:
                        type: string
                  token:
                    type: string
                    description: このtokenをヘッダーに入れて認証
  /account/profile:
    patch:
      tags:
        - アカウント
      summary: 編集
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                user:
                  type: object
                  required:
                    - name
                    - email
                  properties:
                    name:
                      type: string
                      description: 名前
                    email:
                      type: string
                      description: メールアドレス
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    required:
                      - id
                      - name
                      - email
                    properties:
                      id:
                        type: integer
                        format: int32
                      name:
                        type: string
                      email:
                        type: string
                      icon_image:
                        type: string
  /account/icon_image:
    patch:
      tags:
        - アカウント
      summary: プロフィール画像
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: string
                  format: binary
                  description: 画像ファイルをアップロードする
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    required:
                      - id
                      - name
                      - email
                    properties:
                      id:
                        type: integer
                        format: int32
                      name:
                        type: string
                      email:
                        type: string
                      icon_image:
                        type: string
  /posts:
    post:
      tags:
        - 投稿
      summary: 作成
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                post:
                  type: object
                  required:
                    - body
                  properties:
                    body:
                      type: string
                      description: 投稿内容
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    type: object
                    required:
                      - id
                      - body
                      - userId
                      - createdAt
                    properties:
                      id:
                        type: integer
                      body:
                        type: string
                      userId:
                        type: integer
                      createdAt:
                        type: string
                        format: date-time
                      user:
                        type: object
                        required:
                          - id
                          - name
                          - email
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          icon_image:
                            type: string
  /posts/{id}:
    get:
      tags:
        - 投稿
      summary: 取得
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 投稿のID
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  post:
                    type: object
                    required:
                      - id
                      - body
                      - userId
                      - createdAt
                    properties:
                      id:
                        type: integer
                      body:
                        type: string
                      userId:
                        type: integer
                      createdAt:
                        type: string
                        format: date-time
                      user:
                        type: object
                        required:
                          - id
                          - name
                          - email
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          icon_image:
                            type: string
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
